In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [4]:
X = iris.data

In [5]:
y = iris.target

In [6]:
X.shape

(150, 4)

In [7]:
y.shape

(150,)

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 83, 125,  17,  88,  41,  64, 113, 134, 129,  28,  79,  82,  32,
       114, 121, 104,   0, 116,   4,   6,  25, 132,  35, 115,  78, 127,
       123,  98, 120, 118,  21,  42,  29,  12,  37, 103,  92, 111,   5,
       130, 106,  40, 143,  30, 142,  11,  94,  69,  60,  63,  36, 136,
        45, 117,  16,   9,  33, 122,  13,  93,  52,  43,  15,  51,  50,
        75,  58,  97, 147, 128,  89, 137, 135,  61,  56,  70, 107,  14,
        31, 148,  22,   3,  27,  72, 145, 140, 133,  66,  96,  49, 112,
        86,  24,  76,  57, 141, 102, 149,  48,  46,  62,  47, 100, 139,
        18,  10, 144, 105,   8,  26, 124,  59, 126,  80,  91,  19,   7,
        77,  85, 108, 146,  34,  55, 110,  67,  90,  95,  65, 138,  81,
        44,  38,   1,  53, 119,  20,  74,  87,  84,  68,   2,  23,  39,
        71,  73, 109, 101,  99,  54, 131])

In [10]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [11]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [14]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [16]:
from kNN.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [18]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [19]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [21]:
from kNN.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [22]:
y_predict

array([0, 1, 2, 2, 1, 1, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 1, 2,
       0, 0, 1, 2, 1, 1, 2])

In [23]:
sum(y_predict == y_test)

28

In [24]:
sum(y_predict == y_test) / len(y_test)

0.93333333333333335

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [27]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)
